# Generated by Django 5.2.11 on 2026-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_description', models.TextField()),
                ('mode', models.CharField(choices=[('express', 'Express'), ('full', 'Full'), ('autopilot', 'Autopilot')], default='express', max_length=10)),
                ('domain', models.CharField(choices=[('technical', 'Technical'), ('business', 'Business'), ('everyday', 'Everyday')], default='technical', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=15)),
                ('final_report', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
