"""
API views for downloading ARIZ session reports in PDF and DOCX formats.
"""
import logging

from django.http import HttpResponse
from django.utils import timezone
from django.utils.text import slugify
from rest_framework import permissions, status
from rest_framework.response import Response
from rest_framework.views import APIView

from apps.ariz_engine.models import ARIZSession
from apps.users.permissions import CanGenerateReport

from .generators import DOCXReportGenerator, PDFReportGenerator
from .models import GeneratedReport
from .serializers import GeneratedReportSerializer

logger = logging.getLogger(__name__)


class BaseReportDownloadView(APIView):
    """Base class for report download views.

    Subclasses must set ``report_format`` and implement
    ``_get_generator()`` and ``_get_content_type()``.
    """

    permission_classes = [permissions.IsAuthenticated, CanGenerateReport]
    report_format = None

    def get(self, request, session_id):
        """Generate and stream a report for the given session."""
        session = self._get_session(request, session_id)
        if session is None:
            return Response(
                {"detail": "Сессия не найдена."},
                status=status.HTTP_404_NOT_FOUND,
            )

        if session.status != "completed":
            return Response(
                {"detail": "Отчёт доступен только для завершённых сессий."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # Create a report tracking record
        report = GeneratedReport.objects.create(
            session=session,
            requested_by=request.user,
            format=self.report_format,
            status="generating",
        )

        try:
            generator = self._get_generator(session)
            report_bytes = generator.generate()
        except Exception as exc:
            logger.exception(
                "Failed to generate %s report for session %s",
                self.report_format,
                session_id,
            )
            report.status = "failed"
            report.error_message = str(exc)[:500]
            report.save()
            return Response(
                {"detail": f"Ошибка генерации отчёта: {exc}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # Update report record on success
        report.status = "completed"
        report.file_size = len(report_bytes)
        report.completed_at = timezone.now()
        report.save()

        filename = self._build_filename(session)
        content_type = self._get_content_type()

        response = HttpResponse(report_bytes, content_type=content_type)
        response["Content-Disposition"] = f'attachment; filename="{filename}"'
        response["Content-Length"] = len(report_bytes)
        return response

    def _get_session(self, request, session_id):
        """Fetch session, verifying that the requesting user owns it."""
        try:
            return ARIZSession.objects.select_related(
                "problem", "problem__user"
            ).get(pk=session_id, problem__user=request.user)
        except ARIZSession.DoesNotExist:
            return None

    def _build_filename(self, session) -> str:
        title_slug = slugify(session.problem.title, allow_unicode=True)[:50]
        date_str = session.created_at.strftime("%Y%m%d")
        return f"ariz-report-{title_slug}-{date_str}.{self.report_format}"

    def _get_generator(self, session):
        raise NotImplementedError

    def _get_content_type(self) -> str:
        raise NotImplementedError


class DownloadPDFView(BaseReportDownloadView):
    """
    GET /api/v1/reports/{session_id}/download/pdf/

    Generate and download a PDF report for the specified ARIZ session.
    """

    report_format = "pdf"

    def _get_generator(self, session):
        return PDFReportGenerator(session)

    def _get_content_type(self) -> str:
        return "application/pdf"


class DownloadDOCXView(BaseReportDownloadView):
    """
    GET /api/v1/reports/{session_id}/download/docx/

    Generate and download a DOCX report for the specified ARIZ session.
    """

    report_format = "docx"

    def _get_generator(self, session):
        return DOCXReportGenerator(session)

    def _get_content_type(self) -> str:
        return (
            "application/vnd.openxmlformats-officedocument"
            ".wordprocessingml.document"
        )


class ReportListView(APIView):
    """
    GET /api/v1/reports/

    List all reports generated by the current user.
    """

    permission_classes = [permissions.IsAuthenticated]

    def get(self, request):
        reports = GeneratedReport.objects.filter(
            requested_by=request.user
        ).select_related("session", "session__problem")
        serializer = GeneratedReportSerializer(reports, many=True)
        return Response(serializer.data)
