# Generated by Django 5.2.11 on 2026-02-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARIZSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('express', 'Express'), ('full', 'Full'), ('autopilot', 'Autopilot')], max_length=10)),
                ('current_step', models.CharField(default='1', max_length=10)),
                ('current_part', models.IntegerField(default=1)),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ARIZ Session',
                'verbose_name_plural': 'ARIZ Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contradiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('surface', 'Surface'), ('deepened', 'Deepened'), ('sharpened', 'Sharpened')], max_length=10)),
                ('quality_a', models.CharField(blank=True, default='', max_length=255)),
                ('quality_b', models.CharField(blank=True, default='', max_length=255)),
                ('property_s', models.CharField(blank=True, default='', max_length=255)),
                ('anti_property_s', models.CharField(blank=True, default='', max_length=255)),
                ('formulation', models.TextField()),
            ],
            options={
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='IKR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation', models.TextField()),
                ('strengthened_formulation', models.TextField(blank=True, default='')),
                ('vpr_used', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'IKR',
                'verbose_name_plural': 'IKRs',
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_used', models.CharField(choices=[('principle', 'Principle'), ('standard', 'Standard'), ('effect', 'Effect'), ('analog', 'Analog'), ('combined', 'Combined')], max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('novelty_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('feasibility_score', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-novelty_score'],
            },
        ),
        migrations.CreateModel(
            name='StepResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_code', models.CharField(max_length=10)),
                ('step_name', models.CharField(max_length=255)),
                ('user_input', models.TextField(blank=True, default='')),
                ('llm_output', models.TextField(blank=True, default='')),
                ('validated_result', models.TextField(blank=True, default='')),
                ('validation_notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
