# Generated by Django 5.2.11 on 2026-02-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ariz_engine', '0001_initial'),
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arizsession',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='problems.problem'),
        ),
        migrations.AddField(
            model_name='contradiction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contradictions', to='ariz_engine.arizsession'),
        ),
        migrations.AddField(
            model_name='ikr',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ikrs', to='ariz_engine.arizsession'),
        ),
        migrations.AddField(
            model_name='solution',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='ariz_engine.arizsession'),
        ),
        migrations.AddField(
            model_name='stepresult',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ariz_engine.arizsession'),
        ),
        migrations.AlterUniqueTogether(
            name='stepresult',
            unique_together={('session', 'step_code')},
        ),
    ]
